### ISSUE TITLE
vscoq 0.2.6: no longer recognizes proof bullets properly

### ISSUE THREAD

**Issue by jonleivent** [siegebell/vscoq#105]
Something regressed from 0.2.5 to 0.2.6 - apparently vscoq is not single stepping into proof bullets properly.

To reproduce - visit wavl-noauto.v, interpret to line 220 (just before Fixpoint find), and step through Fixpoint find.  As it steps into the first proof bullet, it will move too far - moving over the tactic in that bullet without executing it.  Because of this, it can't get past the "reflexivity" on line 224.

**Comment by siegebell** [comment]
0.2.7, containing the fix, is now published
