### ISSUE TITLE
inconsistent document state

### ISSUE THREAD

**Issue by siegebell** [siegebell/vscoq#114]
The STM's internal representation sometimes gets out of sync with the actual document text. This leads to some pretty wacky behavior...

**Comment by siegebell** [comment]
Temporary fix: if this happens, try cutting & pasting several lines around the problem area to try to get the STM to reparse it correctly. If it's really bad: `ctrl+a, ctrl+x, ctrl+v` to reparse the whole document.

**Comment by aa755** [comment]
I have noticed sometimes that the error highlights are mispositioned -- perhaps a symptom of this bug.

**Comment by siegebell** [comment]
If inconsistencies continue to occur, add the following to settings.json:
`"coq.diagnostics.checkTextSynchronization": true`

This will enable an inconsistency check as the document is editing. Then check the console log to see if any inconsistency errors are reported.
