### ISSUE TITLE
Proofview shows nothing after vscode upgrade

### ISSUE THREAD

**Issue by RexZhang4321** [siegebell/vscoq#128]
Hi,

After upgrading my vscode from 1.9.1 to 1.10.0, the proofview then shows nothing now. I really appreciate this plugin and hope it can be fixed soon. Thx!
<img width="1035" alt="screen shot 2017-03-01 at 7 18 12 pm" src="https://cloud.githubusercontent.com/assets/6974303/23487409/e974ac50-feb3-11e6-9e5b-43446375868e.png">

**Comment by RexZhang4321** [comment]
Fixed by vscode update to 1.10.1

**Comment by cogtoto** [comment]
Hello,
My proofview does not work anymore. It opens but shows nothing. Can you please help ?
Many thanks

coqidetop.opt -v
The Coq Proof Assistant, version 8.13.2 (September 2021)
compiled on Sep 25 2021 15:44:45 with OCaml 4.11.1

VSCode
Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:01:43.795Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-16-generic
