### ISSUE TITLE
completion via sinppets

### ISSUE THREAD

**Issue by czhang03** [siegebell/vscoq#134]
I was studying company-coq, I found they are just completing via snippets (when you are didn't turn on coq)

Do you think it would be appropriate to simply translate the code here https://github.com/cpitclaudel/company-coq/blob/master/company-coq-abbrev.el to vscode snippets?

**Comment by siegebell** [comment]
I've already implemented that, plus documentation lookup... but haven't released it because vscoq is released under the MIT License and the documentation is under GPL. I might just move to GPL.

**Comment by czhang03** [comment]
Thank you so much, This is SUUUUUUPER helpful.

I really cannot thank you enough.

**Comment by czhang03** [comment]
Just out of curiosity, when do you plan to add the feature to this plugin? because emacs is just so flickering, I don't know how long I can take...

**Comment by siegebell** [comment]
Ahh... I just got a new job and am waiting for a higher-up to sign off on me working on open source projects on my own time :(

**Comment by czhang03** [comment]
haha, doesn't matter, I can use emacs for couple of month.

Congratulation on your new job.
