### ISSUE TITLE
Can not open proof view

### ISSUE THREAD

**Issue by speedcell4** [siegebell/vscoq#171]
none of my "open proof view" and "open proof view in external browser" works.

the settings look like below,

```
    "coqtop.binPath": "/usr/local/bin/coqtop",
    "coq.loadCoqProject": false,
    "coq.autoRevealProofStateAtCursor": true,
    "coq.editor.indentAfterBullet": "indent",
```

any idea about how to fix this?

**Comment by czhang03** [comment]
Seems like this is no longer maintained.
The new version is at coq-community.
