### ISSUE TITLE
Documentation for Interp command

### ISSUE THREAD

**Issue by zjhmale** [siegebell/vscoq#47]
```
"Interp" :  ((bool * bool) * string)
             -> (Stateid.t * ((string, string) CSig.union))
```

**Comment by siegebell** [comment]
`Interp` is deprecated; do you still think it's worth documenting?

**Comment by zjhmale** [comment]
oh sorry, i did not know that 😅 , i just found it using `coqtop -ideslave --help-XML-protocol`, anything about this command will be entirely removed in Coq8.6 right?
