### ISSUE TITLE
vscoq not picking up _CoqProject properly

### ISSUE THREAD

**Issue by jonleivent** [siegebell/vscoq#89]
I'm testing vscoq against my git project [https://github.com/jonleivent/mindless-coding-phase2](url), using Coq 8.6pl1 (on Debian Jessie).  This project works in PG, PGxml and CoqIDE, but vscoq is apparently not parsing its _CoqProject file properly.  After building the project, when visiting the script wavl_noauto.v, and trying to step through it, I immediately get the error: Error: unable to locate library elist.  This is using vscoq's default settings, which has loadCoqProject set to true.

**Comment by siegebell** [comment]
This was fixed the other day: https://github.com/siegebell/vscoq/issues/84

I'll publish the update to the vscode marketplace soon.

-cj

On Wed, Nov 30, 2016 at 10:19 AM, Jonathan Leivent <notifications@github.com

**Comment by siegebell** [comment]
dup of #84

**Comment by siegebell** [comment]
published in 0.2.3

**Comment by jonleivent** [comment]
Just picked up 0.2.3, still get the same error.

**Comment by siegebell** [comment]
@jonleivent could you post your _CoqProject here? Thanks

**Comment by siegebell** [comment]
@jonleivent whoops, nevermind. I see your link.

**Comment by siegebell** [comment]
@jonleivent I've added a test case and it seems that the _CoqProject parameters are being passed correctly to coqtop.

Did you tell vscode to open the root folder of the project, where _CoqProject is located, or did you just open a *.v file directly? (If the latter, try the former).

If you still get the error, please select the "Coq Language Server" output pane and copy the results here; particularly the bit (toward the top) that prints the coqtop command line.

Thanks!

**Comment by siegebell** [comment]
Cannot reproduce.

Steps:
```bash
git clone https://github.com/jonleivent/mindless-coding-phase2.git .
make wavl-noauto.vo
code .
```

Then I opened wavl-noauto.v in vscode and was able to step through it all the way to the end.

**Comment by jonleivent** [comment]
After visiting root folder first, it works!  Is this an expected difference?

**Comment by siegebell** [comment]
Yeah, but it's a really unintuitive aspect of vscode :/

I'll see if I can make vscoq a bit smarter when a root folder is not loaded.
